- name: install zsh
  pacman:
    name: zsh,zsh-completions,zsh-autosuggestions,zsh-syntax-highlighting
    state: present

- name: install starship
  pacman:
    name: starship
    state: present

- name: install stow
  pacman:
    name: stow
    state: present

- name: install js pkg mans
  pacman:
    name: yarn,npm
    state: present

- name: install tmux
  pacman:
    name: tmux
    state: present

- name: install new age tools
  pacman:
    name: ripgrep,exa,bat
    state: present

- name: install git
  pacman:
    name: git
    state: present

- name: install rust
  pacman:
    name: rust,cargo
    state: present

- name: pass
  pacman:
    name: pass
    state: present

- name: pkgfile
  pacman:
    name: pkgfile
    state: present

- name: docker
  pacman:
    name: docker,docker-compose
    state: present

- name: Enable docker service
  ansible.builtin.systemd:
    name: docker
    enabled: yes

- name: start docker service
  ansible.builtin.systemd:
    name: docker
    state: started

- name: install fzf
  pacman:
    name: fzf
    state: present
