- name: install bluez
  pacman:
    name: bluez
    state: present

- name: install bluez utils
  pacman:
    name: bluez-utils
    state: present

- name: install blueman
  pacman:
    name: blueman
    state: present

- name: Enable bluetooth service
  ansible.builtin.systemd:
    name: bluetooth
    enabled: yes

- name: start bluetooth service
  ansible.builtin.systemd:
    name: bluetooth
    state: started
